### ISSUE TITLE
[1.21] GroovyModLoader Dependency NeoForge

### ISSUE THREAD

**Issue by Starexify** [MatyrobbrtMods/EatingAnimationForge#16]
Add the GroovyModLoader dependency on CurseForge, so it's downloaded automatically when installing the mod. Because I got always the GML:1 error on 1.21 NeoForge and didn't know why I can't load the mod.
So please add the dependency

**Comment by Matyrobbrt** [comment]
It should be added, I'll check again.

**Comment by Matyrobbrt** [comment]
Should be fixed now, thanks for the heads up.
