### ISSUE TITLE
Not working for some reason ¯\_(ツ)_/¯ lol 

### ISSUE THREAD

**Issue by PEPERONIPEZ** [MatyrobbrtMods/EatingAnimationForge#2]
https://user-images.githubusercontent.com/99416195/153548636-b8b23232-1442-422c-89e6-999173afbc53.mp4

I pasted a video on how it looks(the bad quality is due to reducing size from GitHub not allowing the vid to be higher than 10 mg!( If it doesn't, the video is just me eating with the same vanilla no animation eating, even tho I showed that it was installed maybe the video will help😸)( also yes I did edit it to fast forward my "idiotic slowness?" lol that's the best way to say it I guess)( I added a VHS filter but now it looks like it was filmed from a VHS due to the bad quality although I just added it on the fast forward parts)

**Comment by Matyrobbrt** [comment]
Can you send the `debug.log`. And follow-up, do you have any other mod that might be messing with it (and that includes OptiFine)

**Comment by PaulerLeOne** [comment]
I've had the same problem and I solved it by moving up the "Mod Resources" pack in the resource pack menu.

**Comment by Aulberon** [comment]
Same problem here, moving the "Mod Resources" pack up solved the problem.

This is my resource pack list:
```
Alternative+Rain+Sounds+1.19-1.19.2.zip
Create+Simple+Storage+1.1.zip
Create+Style+Modded+Compats+v16.zip
Create_Building_Gadgets_GUI_and_3D_Items.zip
create_redone_stones_V1.1_1.18.2.zip
cubic-sun-moon-v1-5.zip
Onyx-Sans-v3.zip
Icons+-Menu.zip
Visual+Titles.zip
Icons+1.8pre3.zip
Infernal Resources.zip
EducationalPosters.zip
Rainy+Day+(1_18_1).zip
Tool+Belt+Retextured+1.18.x.zip
xalis Display Corner.zip
Quark Programmer Art.zip
Detail-Brush-1.5-1.19.zip
Enhanced+Tools++Armour.zip
Handful_of_Fixes_(1.19.3).zip
HD Bedspread.zip
More_Nether_Roots_(1.19.3).zip
Particles+V.1.2.3.zip
UniqueDark+1.19.2.zip
VanillaTweaks_r115698.zip

```
It appears to be caused by the "Vanilla Tweaks" resource pack, since moving the "Mod Resources" pack above it, solved the problem.

**Comment by Matyrobbrt** [comment]
Closing as there has been no response from the OP. Most issues can indeed be solved by making sure that the Mod Resources pack is at the top.
