### ISSUE TITLE
Pls add integration with other mods

### ISSUE THREAD

**Issue by InfernumYT** [MatyrobbrtMods/EatingAnimationForge#3]
like:
https://www.curseforge.com/minecraft/mc-mods/ecologics
https://www.curseforge.com/minecraft/mc-mods/alexs-mobs

**Comment by Matyrobbrt** [comment]
All of the current assets are the original Fabric ones. Adding new animations is as simple as a resource pack, however I don't make textures. If you think that you can help with that, contact me on Discord. I will close this issue.
