### ISSUE TITLE
Resource Pack Incompatability.

### ISSUE THREAD

**Issue by Romoslayer** [MatyrobbrtMods/EatingAnimationForge#4]
If possible could you add compatibility for this mod to use the resource pack Jicklus 1.18 food textures?

Video of what happens.
https://www.youtube.com/watch?v=LO922TkizdM&feature=youtu.be

**Comment by Matyrobbrt** [comment]
I don't see any issues?

**Comment by Romoslayer** [comment]
If you look at the bread in my hand it gets changed from the resource packs texture for bread to vanillas.

**Comment by Matyrobbrt** [comment]
> If you look at the bread in my hand it gets changed from the resource packs texture for bread to vanillas.

That's because the resource pack in the mod overrides vanilla and replaces its textures with 3 others. That's intentional, and there's no other way of doing the animations.
