### ISSUE TITLE
1.19 Latest Forge Crash

### ISSUE THREAD

**Issue by MianReplicate** [MatyrobbrtMods/EatingAnimationForge#6]
Currently Eating Animation crashes on the latest versions of Forge upon startup.

Minecraft Version: 1.19
Forge Version: 41.0.96
Mod Version: 3.0.0

Crash Log: https://mclo.gs/hr0mD5g

**Comment by Matyrobbrt** [comment]
Ehm, GitHub didn't close the issue apparently.
