### ISSUE TITLE
Not available for the version every mod should be available for

### ISSUE THREAD

**Issue by Juninh567** [MatyrobbrtMods/EatingAnimationForge#7]
Add 1.12.2
My potato PC can't run modern versions.

**Comment by Matyrobbrt** [comment]
> the version every mod should be available for

> Add 1.12.2

Not even a please? Huh, that's so entitled.
Let's put this bluntly: I barely have time to maintain new versions, and unless you feel like paying me 45€ / hour (yes, that's the average wage for programming jobs), I will under no circumstances port my mods to versions which are *so* outdated that you barely can get a working workspace for them.
And if I may be rude, in the same way you were, get a better PC, you had 5 years.

**Comment by Juninh567** [comment]
Sorry
